apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blueprint-catalog
  title: Blueprint Catalog
  description: OBOS Blueprint (IDP) felles entiteter
  tags:
    - configuration
spec:
  type: configuration
  owner: team-dx
  system: system-blueprint
  lifecycle: experimental
